#!/bin/bash

tpid=`xinput list | grep Touchpad | cut -d'=' -f2 | tr '\t' ' ' | cut -d' ' -f1`
taps=`xinput list-props $tpid | grep "Tapping Enabled (" | cut -d'(' -f2 | cut -d')' -f1`

for tap in $taps; do
    echo "Device $tpid, prop $tap"
    xinput set-prop $tpid $tap 1
done
